apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-elasticsearch-0
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /root/data/nfs-pv-elasticsearch-0
    server: 172.16.5.44
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-elasticsearch-1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /root/data/nfs-pv-elasticsearch-1
    server: 172.16.5.44
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-elasticsearch-2
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /root/data/nfs-pv-elasticsearch-2
    server: 172.16.5.44